"""added Tables 'User' and 'Basket'

Revision ID: 4cfd61f12379
Revises: 0edc4f9681bb
Create Date: 2025-06-15 19:08:13.389428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cfd61f12379'
down_revision: Union[str, None] = '0edc4f9681bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('basket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('foot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['foot_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket')
    op.drop_table('user')
    # ### end Alembic commands ###
