"""fixed

Revision ID: 813d5bcedefc
Revises: 95d8f45c97fc
Create Date: 2025-06-16 14:18:49.816135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '813d5bcedefc'
down_revision: Union[str, None] = '95d8f45c97fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket', sa.Column('stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basket', 'stock')
    # ### end Alembic commands ###
