"""deleted stock in Menu

Revision ID: 95d8f45c97fc
Revises: 4cfd61f12379
Create Date: 2025-06-16 13:24:04.288264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d8f45c97fc'
down_revision: Union[str, None] = '4cfd61f12379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('stock', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
